conda-forge/conda-smithy-feedstock

recipe/meta.yaml
This bumps the version to `conda-smithy` 0.10.5 following [discussion]( https://github.com/conda-forge/conda-smithy/pull/216#issuecomment-231526470 ) with @pelson. Bringing this to your attention @ocefpaf. This should help with our Travis CI API issues. However, feel free to pull it if needed as I will be out most of today.
=> Bump to 0.10.5

recipe/meta.yaml
Restrict the `conda-build` version based on a [similar update]( https://github.com/conda-forge/conda-smithy/blob/v1.1.2/conda_smithy.recipe/meta.yaml#L23 ) in the recipe from the source repo.
=> Restrict acceptable `conda-build` versions

recipe/meta.yaml
```rst
* Fixes some permissions issues on Windows.
* Stages re-rendering changes if a git repo is in use.
* Adds an option to commit re-rendering changes.
* Committing can be done in edit mode or automatically.
* By default committing is done in edit mode.
```
=> Release 1.4.0

README.md, appveyor.yml, recipe/meta.yaml
```markdown
* Use AppVeyor's Miniconda. #370
* Pull from conda-forge channel first. #370
* Whitespace fix. #326
* Validate `license_family`. #339
* Raise extraneous "license" references. #334
* Check for terminal newline. #371
* Add tests for feedstock file IO. #357
* Report test coverage. #369
* Improved unicode support. #366
* Drop `nose` testing requirement. #368
* Use `unittest` for CI. #367
* Explain `--commit` option for re-rendering. #341
```
=> Release 1.5.0

.gitattributes, README.md, appveyor.yml, recipe/meta.yaml
```markdown
v1.6.0
* Add `.gitattributes` to format recipe line endings. #380
* Cleanup overridden environment variables from `appveyor.yml`. #384
* Put `conda-smithy` version in initial commit of feedstock. #388
* Move feedstock badges to the top of the README. #390
```
Also re-rendered with `conda-smithy` version `1.6.0`.
=> Release 1.6.0

recipe/meta.yaml
```markdown
v1.7.0
* Add support for re-rendering conda-forge-build-setup. #285
```
=> Release 1.7.0

.travis.yml, appveyor.yml, ci_support/run_docker_build.sh, recipe/meta.yaml
```markdown
* Bump the Travis CI image to 10.10 XCode 6.4. #391
* Add quotes for shell expansion in Docker build script. #398
* Fixes for `conda` 4.2.x. #394
* Fix source channel order in CIs to match `conda-forge.yml`. #399
* Tidying up of AppVeyor config. #402, #404, #427
* Require `defaults` in source channels explicitly. #400
* Update suggested commit command to be OS agnostic. #408
* Unpin `setuptools` in `conda-smithy`'s CI. #356
* Fix EOL handling for Windows. #407
* Re-render with source channels and interpret `defaults`. #401
* Provide better Python 3.6 support. #422
* Enable CircleCI setting for PRs from forks. #420
* Drop Python 3.4. #421
* Drop NumPy 1.10. #418
* Specify number of extra lines in lint. #416
* Fix Homebrew uninstall to ignore dependencies. #428
```
=> Release 2.0.0

.travis.yml, LICENSE, recipe/meta.yaml
```markdown
* Explicitly disable secrets on CircleCI. #445
* Use Homebrew's uninstall script to quickly and quietly remove it. #443
* Fix a typo in `feedstocks` help. #446
* Add license date ranges. #439
* Fix a formatting issue in the README regarding channel targets. #432
```
=> Release 2.0.1

.travis.yml, appveyor.yml, ci_support/fast_finish_ci_pr_build.sh, ci_support/run_docker_build.sh, circle.yml, recipe/meta.yaml
```markdown
* Combine CircleCI re-renders and minor cleanup. #457, #456
* Fix some typos in the `feedstocks` script. #458
* Handle `r-base`. #453
* Fast finish old PR builds on CIs. #455
* Ensure CircleCI fails early terminated builds. #454, #459
```
=> Release 2.1.0

recipe/meta.yaml
```markdown
* Allow to tweak docker executable in run_docker_build. #463
* Minor cleanup of GitHub registration. #478
* Provide empty matrix on skip. #479
* Bypass setup.py when testing. #413
* Handle team additions. #466
```
=> Release 2.2.0

appveyor.yml, recipe/meta.yaml
```markdown
* Pin Miniconda to 4.2.12 in CI. #491
* Pin conda-build 2.1.4 with conda 4.1.x on CI. #490
* Download fast finish script with PowerShell. #489
* Require conda-build-all 1.0.2+. #483
* Use AppVeyor's Miniconda with Python 3.6. #474
```
=> Release 2.2.1

recipe/meta.yaml
```markdown
* Depend on conda-build-all 1.0.3. #493
* Revert "Provide empty matrix on skip" (#479). #493
```
=> Release 2.2.2

appveyor.yml, ci_support/run_docker_build.sh, recipe/meta.yaml
```markdown
* Mention that re-rendering does not need CI tokens set up. #495
* Drop Obvious CI compiler activation on AppVeyor. #392
* Let the travis-ci response fail to be json. #498
* Check http response codes in more places. #503
* Supporting building as a non-root user. #296
* Check for conda < 4.3. #502
* Remove call to api.travi-ci.org/hooks. #505
```
=> Release 2.3.0

recipe/meta.yaml
Appears we are getting `conda` links leftovers packaged with `conda-smithy` due to a bug in `conda-build` 2.1.9. Please see issue ( https://github.com/conda/conda-build/issues/1916 ) for more details. As a workaround, manually remove these links and rebuild the package.
=> Remove conda symlinks

recipe/meta.yaml
```markdown
* Correct typos in RegisterCI summary message. #510
* Remove redundant synching. #508
```
Closes https://github.com/conda-forge/conda-smithy/issues/513
cc @isuruf
=> Release 2.3.1

.ci_support/linux_.yaml, .circleci/run_docker_build.sh, README.md, recipe/meta.yaml
Checklist
Releases 3.1.2 of `conda-smithy`. Adds the `conda-forge-pinning` package as dependency (was omitted accidentally before). Other changes in the release notes.
=> Release 3.1.2

recipe/meta.yaml
Adds the `vsts-python-api` requirement, which is needed for `conda-smithy` 3.2's Azure support.
xref: https://github.com/conda-forge/conda-smithy-feedstock/pull/116#issuecomment-447536000
Checklist
=> Require `vsts-python-api`

recipe/meta.yaml
This is a minor fix for conda-build 3, which really shouldn't matter too much for the packages built. Namely this switches to using `host` to list the build dependencies that live in the same environment that the package will be installed in.
Checklist
=> Rename `build` to `host`

recipe/meta.yaml
As conda-smithy now is Python 3 only and requires at least Python 3.5, make that a minimum version for building and installing conda-smithy.
Note: We should probably pull older conda-smithy 3.2 packages that do not have this constraint so that users do not accidentally install these under Python 2 and run into problems.
Checklist
=> Require Python 3.5+

recipe/meta.yaml
It looks like `m2-git` is broken for users as demonstrated by the discussion at the end of PR ( https://github.com/conda-forge/conda-smithy-feedstock/pull/277 ). However `git` breaks other MSYS2 packages used in conda-forge ( https://github.com/conda-forge/git-feedstock/issues/135 ). So for now this drops git on Windows altogether ( https://github.com/conda-forge/conda-smithy-feedstock/issues/290#issuecomment-2128210093 ). Hopefully we can find a better solution for Windows users with git in the future
<hr>
Checklist
=> Drop git on Windows

recipe/meta.yaml
Checklist
This PR adds running of the pytest to the recipe test section. This is useful so that we can run downstream tests from dependencies to guard against accidental breakage. 
I also added `pydantic >=2,<3` to the run requirements. This is also the case in the [upstream `environment.yaml`.](https://github.com/conda-forge/conda-smithy/blob/7b0b83038ae6c012c72bc13cca6641fb81dc7e08/environment.yml#L35C5-L35C20)
=> Run pytest tests

recipe/meta.yaml
This breaks `downstreams:` testing in `conda`, see https://github.com/conda-forge/conda-feedstock/pull/243
=> don't require `python {{ python_min }}` in testing; breaks `downstreams:` usage
