appveyor.yml
This PR updates AppVeyor's template using latest master conda-smithy.
=> Regenerate recipe

recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
For consistency with the other recipes.
=> Minor fixes

recipe/meta.yaml
=> Updated to v1.0.2

recipe/meta.yaml
* Use `conda-build`'s `entrypoints`.
* Include license file and specify license family in metadata.
* Change indentation to 2 spaces.
=> Recipe cleanup

recipe/meta.yaml
```markdown
* Fixed file removal for some cases with the git repo's index.
```
=> Release 1.4.4

appveyor.yml, recipe/meta.yaml
```markdown
* Use permalink for bootstrap download link.
```
=> Release 1.4.5

recipe/meta.yaml
```markdown
* Create any needed directories to write a file.
* Prune any empty directories left when removing a file.
* Clean up the development recipe to more closely match the feedstock.
* Use GitPython's `BlobFilter` to search for a particular file path.
* Fix `python setup.py test` to work correctly with `unittest`.
```
=> Release 1.4.6

bootstrap-obvious-ci-and-miniconda.py
Do not remove! This is harmless to live here and people do need it outside of conda-forge too!
=> Vendorize bootstrap again

recipe/meta.yaml
```markdown
* Fix some strange permission issues with `git`. #383
```
=> Release 1.5.3

recipe/meta.yaml
```markdown
*  Support conda 4.3. #523
```
=> Release 2.3.2

recipe/meta.yaml
See https://github.com/conda-forge/conda-smithy/releases/tag/v2.3.3
=> update to 2.3.3

recipe/meta.yaml
To make sure `noarch:python` works as intended.
cc @ocefpaf
=> Update conda-build-all condition

recipe/meta.yaml
=> Update to 2.4.3

recipe/meta.yaml
=> Release 3.1.4

.circleci/run_docker_build.sh, recipe/meta.yaml
=> Release 3.1.5

recipe/meta.yaml
Just checking new conda-forge-webservices stuff
=> [skip ci] [ci skip] add isuruf-bot

recipe/meta.yaml
=> [skip CI] [CI skip] update maintainers team

.github/CODEOWNERS
Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #149.
Here's a checklist to do before merging.
Fixes #149
=> MNT: rerender

recipe/1100.patch, recipe/meta.yaml
=> Add patch for recipes starting with _

recipe/meta.yaml
Checklist
Likely fixes:
- https://github.com/conda-forge/pingouin-feedstock/pull/7
ref:
- https://github.com/conda-forge/conda-smithy/pull/1104#issuecomment-509835833
Please also update dependencies in upstream repository.
=> requirements: update to conda-build>=3.18.3, add toolz

recipe/meta.yaml
=> Remove license hint patch

recipe/meta.yaml
=> BUG remove shellcheck

.gitattributes, build-locally.py, recipe/meta.yaml
=> ENH bump to 3.14.3

recipe/meta.yaml
=> ENH v3.21.0

recipe/meta.yaml
=> ENH v3.21.2

recipe/meta.yaml
Checklist
https://github.com/conda-forge/conda-smithy/releases/tag/v3.22.1
=> conda-smithy 3.22.1

recipe/meta.yaml
=> conda-smithy 3.26.0

.scripts/build_steps.sh, .scripts/logging_utils.sh, recipe/meta.yaml
=> conda-smithy 3.26.1

recipe/meta.yaml
=> conda-smithy 3.26.2

recipe/meta.yaml
=> conda-smithy 3.27.0

recipe/meta.yaml
=> conda-smithy 3.27.1

recipe/meta.yaml
Checklist
---
It was added upstream in `environment.yml` but yesterday's bot PR was automerged
https://github.com/conda-forge/conda-smithy/blob/85ddb5deabda9ab58ae6ec898e2a1e33393117b7/environment.yml#L36
xref: #281, https://github.com/conda-forge/conda-smithy/issues/1866
I didn't rerender because it was just rerendered yesterday
=> v3.32.0 requires jsonschema

recipe/meta.yaml
=> Bump to 3.50.0
